baseURL = "http://example.org/"
languageCode = "ru-ru"
title = "My New Hugo Site"
disableKinds = ["taxonomy", "taxonomyTerm"]
theme = "piclab_orbitor"

[params]
[params.home_banner]
   title = 'Комания PicLab'
   subtitle = ''
   description = 'Добавим технологии искусственного интеллекта в бизнес-процессы вашей компании.'
   btn_text = 'Подробнее про PicLab'

[[params.home_about]]
    icon = 'ti-light-bulb'
    title = 'Прототип'
    description = 'Совместная экспертная оценка проблем и задач, подготовка технического задания.'
    link_text = 'Подробнее'

[[params.home_about]]
    icon = 'ti-panel'
    title = 'Пилотный проект'
    description = 'Разработка и обучение алгоритмов искусственного интеллекта, создание программного обеспечения и технической документации.'
    link_text = 'Читать далее'

[[params.home_about]]
    icon = 'ti-headphone-alt'
    title = 'Промышленное внедрение'
    description = 'Интеграция программного обеспечения в существующую ИТ-инфраструктуру организации заказчика.'
    link_text = 'Ещё подробнее...'

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

